# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [1]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [2]:
import numpy as np

**2. Print the numpy version and the configuration**

In [4]:
print(np.version.version)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/aleakos/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/aleakos/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/aleakos/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/aleakos/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/aleakos/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/aleakos/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/aleakos/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/aleakos/anaconda3/include']
None


**3. Create a 1D array of zeros of size 10 of type float32**

In [6]:
x = np.zeros(10, dtype=np.float32)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Print the memory size of the array below**

In [9]:
Z = np.zeros((32,12))
print("Z memory size:", Z.nbytes)

Z memory size: 3072


**5. Create a 1D array with values ranging from 10 to 58**

In [11]:
x = np.arange(10, 59, 1)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [14]:
a = np.arange(10)
# Include your solution below
print(a)
a = a[::-1]
print(a)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [15]:
np.resize(np.arange(0, 9), (3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**8. Create a 3x3 identity matrix**

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**9. Find and print the maximum values of each column in the array below** 

In [21]:
Z = np.random.random((10,11))
# Include your solution below
print(Z.max(axis=0))

[0.95810321 0.82624763 0.86196232 0.8641775  0.98904168 0.64974843
 0.79357469 0.94851345 0.95722724 0.90964716 0.86031592]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [25]:
outer = np.ones((7,7))
outer[1:-1, 1:-1] = 0
outer

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [26]:
Z = np.ones((5,5))
Z_pad = np.pad(Z, 1)
# Include your solution below
print(Z_pad)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**

In [27]:
Z = np.random.uniform(0,10,10)
# Include your solution below
Z_int = Z.astype(int)
print(Z)
print(Z_int)

[0.83559094 2.85960412 3.43197277 8.0120103  5.0086377  6.68549158
 1.66871072 8.25486526 0.79571566 2.01977178]
[0 2 3 8 5 6 1 8 0 2]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [32]:
a = np.arange(5)
print(f'Initial array from 0 to 4: \n {a}')

# Use the np.tile command to extend to five rows.

a_tiled = np.tile(a,(5,1))
print(f'Final Array: \n {a_tiled}')


Initial array from 0 to 4: 
 [0 1 2 3 4]
Final Array: 
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [34]:
print(np.linspace(0, 1, num=11, endpoint=False)[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [35]:
print(np.sort(np.random.random(10)))

[0.03722383 0.05939079 0.20979187 0.26574904 0.47666185 0.48080327
 0.55185466 0.69159834 0.82959134 0.94904604]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [45]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan(Y,X)

print(f"R:{R}\n\nT:{T}")


R:[0.51382273 0.11698673 1.14129196 1.07100093 0.40645957 0.20678859
 0.5927509  0.98851366 0.09617733 0.98439849]

T:[0.36466413 0.11318542 0.7731222  0.39194786 0.07401339 0.13742994
 0.04706032 0.51570898 0.06695079 0.37185087]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [46]:
arr = np.random.random(10)
print(arr)
arr[np.where(arr==np.max(arr))] = 0
print(arr)

[0.74688537 0.34841344 0.53167455 0.76766046 0.49126962 0.92956533
 0.06105373 0.64540037 0.32203253 0.56976322]
[0.74688537 0.34841344 0.53167455 0.76766046 0.49126962 0.
 0.06105373 0.64540037 0.32203253 0.56976322]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [48]:
Z = np.random.uniform(0,1,10)
z = 0.5
print(f"Original Z: \n{Z}")
# Include your solution below

x = np.abs(Z-z)  # find distance of all elements to z
index_min = np.argmin(x)  # find smallest distance
nearest = Z[index_min]
print(f"\nNearest value to z in Z: {nearest}")

Original Z: 
[0.02572191 0.61460964 0.24317024 0.48553927 0.51370834 0.53524417
 0.67105996 0.57944407 0.95073791 0.31150553]

Nearest value to z in Z: 0.5137083351364097


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [49]:
# changed this so its the same as above
Z = np.arange(1,6)[::-1]
# Include your solution below
res = np.zeros(4*(len(Z)), dtype=int)
# broadcast
res[::4] = Z
solution = res[:-3]
print(solution)

[5 0 0 0 4 0 0 0 3 0 0 0 2 0 0 0 1]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [22]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
b = B[:,:,np.newaxis]
sol = A*b
print(sol)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [53]:
W = np.arange(30).reshape(6,5)
print(W, "\n")
# Include your solution below
W[[1, 0]] = W[[0, 1]]
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] 

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [59]:
def bbox(img):
    #include your solution below
    non_zeros = np.nonzero(img)
    print(f"Shape: {img.shape}")
    r1, r2 = non_zeros[0].min(), non_zeros[0].max()
    c1, c2 = non_zeros[1].min(), non_zeros[1].max()
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

Shape: (383, 490)
((29, 50), (342, 431))


**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [60]:
def moving_average(x,N = 3):
    #define your function here
    return np.mean(x.reshape(-1, N), axis=1)

a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [61]:
C = np.bincount([1,1,2,3,4,4,6])
# Include your solution here
A = np.repeat(np.arange(0,len(C)), C)
print(A)

[1 1 2 3 4 4 6]


**25. Find the most frequent value in the array below?**

In [73]:
Z = np.random.randint(0,10,50)
print(Z)
# Include your solution below
# Use np.bincount to find frequency.
C = np.bincount(Z)
C_max = C.max()

# Identify index (which is value) associated with maximum frequency.
most_f = np.where(C == C_max)[0]

print(f'The most common value(s) is/are {most_f}, ocurring {C_max} times.')

[2 7 3 5 2 4 8 8 4 3 9 7 9 3 0 9 0 7 2 1 9 1 8 6 6 1 8 6 3 8 6 5 4 9 0 2 6
 7 0 3 8 0 4 0 0 9 9 2 8 5]
The most common value(s) is/are [0 8 9], ocurring 7 times.


**26. Write a function to return the n largest values of an array** 

In [74]:
def nlargest(a,n = 5):
    # Include your solution here
    return np.partition(a, -n)[-n:]


Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))

[9995 9996 9997 9998 9999]
